version: '3.8'

services:
  # 1. Web Application (Chứa cả Nginx và PHP-FPM chạy qua Supervisor)
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: bookstore_app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8000:80" # Trỏ cổng 8000 của máy bạn vào cổng 80 của Nginx bên trong container này
    volumes:
      - ./:/var/www/html # Map code local vào để sửa code nhận luôn không cần build lại
    networks:
      - bookstore-network
    depends_on:
      - db

  # 2. MySQL Database (Giữ nguyên không đổi)
  db:
    image: mysql:8.0
    container_name: bookstore_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: bookstore_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: userpassword
      MYSQL_USER: user
    volumes:
      - dbdata:/var/lib/mysql
      # Tự động import file sql khi khởi tạo lần đầu
      - ./bookstore.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    networks:
      - bookstore-network

networks:
  bookstore-network:
    driver: bridge

volumes:
  dbdata: